### ISSUE TITLE
Clarification on training code

### ISSUE THREAD

**Issue by reachomk** [VisualComputingInstitute/diffusion-e2e-ft#12]
Hi, 

I noticed these lines of code in the training script. 

```
                unet_input = (
                    torch.cat((rgb_latents, noisy_latents), dim=1).to(accelerator.device)
                    if args.noise_type is not None
                    else rgb_latents
                )   
                model_pred = unet(unet_input, timesteps, encoder_hidden_states, return_dict=False)[0]

```

I am wondering if you guys experimented with setting args.noise_type to None and forwarding just the RGB latents. If so, did you guys see any performance difference with args.noise_type = "zeros"?

Thanks in advance!

**Comment by kabouzeid** [comment]
Theoretically, both are nearly equivalent. I believe we tested it as well to be sure and found no measurable difference. Moving forward, I'd suggest dropping the zeros, as we left them in there primarily for maximum comparability with Marigold.
