### ISSUE TITLE
The marigold depth model always produce "nan" 

### ISSUE THREAD

**Issue by hirotong** [VisualComputingInstitute/diffusion-e2e-ft#2]
Hi, Thanks for the great work!
I found some problems with the `marigold-e2e-ft-depth` model that it always gives "nan" prediction.
I checked everything is fine before calling the `unet`
But I got all "nan" in the `noise_pred`.
The default configuration is used and I also tried the online demo using the same model and it worked amazing.

Could you please help with the issue?

Thanks,

**Comment by emadellaloggia** [comment]
maybe this will help
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
If you don't have the c compliator, install it.(gcc or clang)

**Comment by hirotong** [comment]
> maybe this will help https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic If you don't have the c compliator, install it.(gcc or clang)

Hi, can you check the link? I can't open it.

**Comment by hirotong** [comment]
Problem solved. Turned out to be some problems with the model weights. I re-download the weights and the problem disappears.
